import Head from "next/head";

import styles from "../styles/Home.module.css";
import Box from "../components/Box";
import Hero from "../components/Hero";
import Works from "../components/Works";
import Contact from "../components/Contact";
import Drawing from "../components/Drawing";
import Education from "../components/Education";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
        ></link>
      </Head>
      <Hero />
      <Box />
      <Drawing />
      <Education />
      <Works />
      <Contact />
    </div>
  );
}
